//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class webserviceEntities : DbContext
    {
        public webserviceEntities()
            : base("name=webserviceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Produto> Produto { get; set; }
        public DbSet<ProdutoCategoria> ProdutoCategoria { get; set; }
    
        public virtual ObjectResult<uspConsultarProduto_Result> uspConsultarProduto(Nullable<int> iNintProdutoID, string iNvchDescricao, Nullable<int> iNintProdutoCategoriaID)
        {
            var iNintProdutoIDParameter = iNintProdutoID.HasValue ?
                new ObjectParameter("INintProdutoID", iNintProdutoID) :
                new ObjectParameter("INintProdutoID", typeof(int));
    
            var iNvchDescricaoParameter = iNvchDescricao != null ?
                new ObjectParameter("INvchDescricao", iNvchDescricao) :
                new ObjectParameter("INvchDescricao", typeof(string));
    
            var iNintProdutoCategoriaIDParameter = iNintProdutoCategoriaID.HasValue ?
                new ObjectParameter("INintProdutoCategoriaID", iNintProdutoCategoriaID) :
                new ObjectParameter("INintProdutoCategoriaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspConsultarProduto_Result>("uspConsultarProduto", iNintProdutoIDParameter, iNvchDescricaoParameter, iNintProdutoCategoriaIDParameter);
        }
    }
}
