'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.18408
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace webService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="webserviceProduto", ConfigurationName:="webService.wsProdutoSoap")>  _
    Public Interface wsProdutoSoap
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento ConsultarProdutoResult no namespace webserviceProduto não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="webserviceProduto/ConsultarProduto", ReplyAction:="*")>  _
        Function ConsultarProduto(ByVal request As webService.ConsultarProdutoRequest) As webService.ConsultarProdutoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="webserviceProduto/ConsultarProduto", ReplyAction:="*")>  _
        Function ConsultarProdutoAsync(ByVal request As webService.ConsultarProdutoRequest) As System.Threading.Tasks.Task(Of webService.ConsultarProdutoResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarProdutoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarProduto", [Namespace]:="webserviceProduto", Order:=0)>  _
        Public Body As webService.ConsultarProdutoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As webService.ConsultarProdutoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class ConsultarProdutoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarProdutoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarProdutoResponse", [Namespace]:="webserviceProduto", Order:=0)>  _
        Public Body As webService.ConsultarProdutoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As webService.ConsultarProdutoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="webserviceProduto")>  _
    Partial Public Class ConsultarProdutoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarProdutoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarProdutoResult As String)
            MyBase.New
            Me.ConsultarProdutoResult = ConsultarProdutoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsProdutoSoapChannel
        Inherits webService.wsProdutoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsProdutoSoapClient
        Inherits System.ServiceModel.ClientBase(Of webService.wsProdutoSoap)
        Implements webService.wsProdutoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function webService_wsProdutoSoap_ConsultarProduto(ByVal request As webService.ConsultarProdutoRequest) As webService.ConsultarProdutoResponse Implements webService.wsProdutoSoap.ConsultarProduto
            Return MyBase.Channel.ConsultarProduto(request)
        End Function
        
        Public Function ConsultarProduto() As String
            Dim inValue As webService.ConsultarProdutoRequest = New webService.ConsultarProdutoRequest()
            inValue.Body = New webService.ConsultarProdutoRequestBody()
            Dim retVal As webService.ConsultarProdutoResponse = CType(Me,webService.wsProdutoSoap).ConsultarProduto(inValue)
            Return retVal.Body.ConsultarProdutoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function webService_wsProdutoSoap_ConsultarProdutoAsync(ByVal request As webService.ConsultarProdutoRequest) As System.Threading.Tasks.Task(Of webService.ConsultarProdutoResponse) Implements webService.wsProdutoSoap.ConsultarProdutoAsync
            Return MyBase.Channel.ConsultarProdutoAsync(request)
        End Function
        
        Public Function ConsultarProdutoAsync() As System.Threading.Tasks.Task(Of webService.ConsultarProdutoResponse)
            Dim inValue As webService.ConsultarProdutoRequest = New webService.ConsultarProdutoRequest()
            inValue.Body = New webService.ConsultarProdutoRequestBody()
            Return CType(Me,webService.wsProdutoSoap).ConsultarProdutoAsync(inValue)
        End Function
    End Class
End Namespace
